server {
    # Escuchar en el puerto seguro
    listen 443 ssl;
    server_name ctaboada.42.fr;

    # Rutas a los certificados que creaste en el Dockerfile
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Carpeta raíz donde WordPress guardó sus archivos
    root /var/www/wordpress;
    index index.php index.html index.htm;

    # Si no encuentra la ruta exacta, devuelve error 404
    location / {
        try_files $uri $uri/ =404;
    }

    # Redirigir las peticiones de archivos PHP al contenedor de WordPress
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}